[package]
name = "tpt-mbd-validation"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
tpt-mbd-core = { workspace = true }
tpt-mbd-joints = { workspace = true }
tpt-mbd-contact = { workspace = true }
tpt-mbd-flexible = { workspace = true }
tpt-mbd-system = { workspace = true }
tpt-math-linalg-fixed = { workspace = true }
tpt-math-linalg-dense = { workspace = true }

[lints]
workspace = true